setwd("D:/Git-data/MovieReviewSentimentRankings/results")
library(Kendall)
data = read.csv(paste(getwd(),"/runFailedOp10_result",sep=''), header = TRUE)
data$p_4 <- data$X.4/(data$X.4+data$X.3+data$X.2+data$X.1+data$X.0)
data$p_3 <- data$X.3/(data$X.4+data$X.3+data$X.2+data$X.1+data$X.0)
data$p_2 <- data$X.2/(data$X.4+data$X.3+data$X.2+data$X.1+data$X.0)
data$p_1 <- data$X.1/(data$X.4+data$X.3+data$X.2+data$X.1+data$X.0)
data$p_0 <- data$X.0/(data$X.4+data$X.3+data$X.2+data$X.1+data$X.0)
Kendall(data$rating, data$p_4)
Kendall(data$rating, data$p_0)
Kendall(data$revenue, data$p_4)
Kendall(data$revenue, data$p_0)
sum(data$X.timeout)/(sum(data$X.timeout)+sum(data$X.0)+sum(data$X.1)+sum(data$X.2)+sum(data$X.3)+sum(data$X.4))
